FROM rio:2

EXPOSE 9000

COPY . /opt/dem

RUN pip3 install FastAPI uvicorn
WORKDIR /opt/dem/src

# Command to run the FastAPI application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]
