FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends gdal-bin && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json tsconfig.json ./
RUN npm install

COPY src ./src

EXPOSE 8002

CMD ["npm", "run", "dev"]
