worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 8011;
        server_name localhost;

        root "C:/Program Files/GlbDemo/data";

        location / {
            autoindex on;
        }
    }
}
